name: create

on:
  create:
    tags:
      - v*

jobs:
  create-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "$GH_CONTEXT" | jq .
        env:
          GH_CONTEXT: ${{ toJSON(github.event) }}
